name: matrix testing 6 jobs

concurrency: 
    group: my sample
    cancel-in-progress: false
on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    strategy:
      fail-fast : false
      max-parallel: 2

      matrix:
        os : [ubuntu-latest, ubuntu-24.04, windows-latest]
        images : [hello-world,alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04
        
    runs-on: ${{matrix.os}}

    steps:
        
      - name: Pull ${{matrix.images}}
        run: |
          echo "Pulling Docker image..."
          docker pull ${{matrix.images}}
          
      - name: Run image on ${{matrix.os}}
        run: |
          echo "Running Docker image..."
          docker run ${{matrix.images}}
          
