name: matrix testing 6 jobs

concurrency: 
    group: my sample
    cancel-in-progress: false
on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    strategy:
      matrix:
        os : [ubuntu-latest, ubuntu-20.04, windows-latest]
        images : [hello-world,alpine]
    runs-on: ${{matrix.os}}

    steps:
        
      - name: Pull ${{matrix.images}}
        run: |
          echo "Pulling Docker image..."
          docker pull ${{matrix.images}}
          
      - name: Run image on ${{matrix.os}}
        run: |
          echo "Running Docker image..."
          docker run ${{matrix.images}}
          
