name: Run Docker Sample

concurrency: 
    group: my sample
    cancel-in-progress: true
on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    strategy:
      matrix:
        os : [ubuntu-latest, ubuntu-20.04, windows-latest]
        images : [hello-world,alpine]
    runs-on: ${{matrix.os}}

    steps:
        
      - name: Pull and run hello-world image
        run: |
          echo "Pulling Docker image..."
          docker pull hello-world
          
          echo "Running container..."
          docker run hello-world
          
