name: Run Docker Sample

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and run hello-world image
        run: |
          echo "Pulling Docker image..."
          docker pull hello-world
          
          echo "Running container..."
          docker run hello-world
          sleep 600s
